
[connections.postgresql]
dialect = "postgresql"
type = "sql"
host = "ep-delicate-scene-a43o2df1.us-east-1.aws.neon.tech"
port = "5432"
database = "apo3"
username = "icesi-viajes_owner"
password = "ji6kwCcDPs5o"

[api_keys]
gemini = "AIzaSyCRrwhzfaYQR2VbWIQLvvBA9LRrhtK_NVk"

[security]
jwt_secret = "ClaveMuyMuySegura"